spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: reservation
              uri: lb://reservation
              predicates:
                - Path=/reservation/**
              filters:
                - TokenRelay= # Repassa o token para o serviço de destino

            - id: catalog-api
              uri: lb://catalog
              predicates:
                - Path=/catalog/**
              filters:
                - TokenRelay=

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: p0Ae5i2OIdns4KP9yWWoKznDzOXAwpJH
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/auth
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    urls:
      - name: catalog-service
        url: /catalog/v3/api-docs
      - name: reservation-service
        url: /reservation/v3/api-docs
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
    oauth:
      client-id: swagger
      client-secret: kx17vvzOnTwrNs1TKPmjg9XgN0ncky08
      appName: Swagger
      scopes: openid, profile, email
    use-pkce: false
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
