spring:
  application:
    name: reservation
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_db
    username: cinema
    password: cinema
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # Garante que o script rode DEPOIS que o Hibernate criar as tabelas
    defer-datasource-initialization: true
  # Força a execução do script sempre
  sql:
    init:
      mode: always

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  oauth:
    client-id: swagger
    scopes: openid, profile, email
  # Força todas as requisições do Swagger a serem feitas via gateway
  override-with-generic-response: false

server:
  port: 62124
  servlet:
    context-path: /reservation
  # Configura o servidor público como sendo o gateway
  forward-headers-strategy: framework


cinema:
  reservation:
    lock-timeout: 300

clients:
  batch:
    url: "http://localhost:8080/catalog/batch"
  catalog:
    url: "http://localhost:8080/catalog"

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000

webhook:
  secret: ${PAYMENT_SECRET_WEBHOOK:sua_secret_webhook}
  publicKey: t9dXRhHHo3yDEj5pVDYz0frf7q6bMKyMRmxxCPIPp3RCplBfXRxqlC6ZpiWmOqj4L63qEaeUOtrCI8P0VMUgo6iIga2ri9ogaHFs0WIIywSMg0q7RmBfybe1E5XJcfC4IW3alNqym0tXoAKkzvfEjZxV6bE0oG2zJrNNYmUCKZyV0KZ3JS8Votf9EAWWYdiDkMkpbMdPggfh1EqHlVkMiTady6jOR3hyzGEHrIz2Ret0xHKMbiqkr9HS1JhNHDX9
